from typing import Protocol, Optional, Any


class TvShowScraper(Protocol):
    def __init__(self, *, plugin_handle: int, settings: Any): ...
    def find(self, *, title: str, year: Optional[str] = None): ...
    def getdetails(self, *, url: str): ...
    def getepisodelist(self, *, url: str): ...
    def getepisodedetails(self, *, url: str): ...
    def nfourl(self, *, nfo: str): ...
    def getartwork(self, *, id: str): ...
